[package]
name = "requestr"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
foundationr = {path = "../foundationr",features=["nsurlsession"]}
objr = {git = "https://github.com/drewcrawford/objr.git"}
blocksr = {path = "../blocksr",features=["continuation"]}
tempfile = "3.2.0"
pcore = {path = "../pcore"}

[dev-dependencies]
kiruna = {path = "../kiruna",features=["test"]}