[package]
name = "requestsr"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
foundationr = {path = "../foundationr",features=["nsurlsession","async"]}
objr = {path = "../objr"}
blocksr = {path = "../blocksr",features=["continuation"]}

[dev-dependencies]
kiruna = {path = "../kiruna",features=["test"]}